language: node_js
node_js:
  - '12'
branches:
  only:
    - master
before_script:
  - npm install -g @nestjs/cli
script:
  - npm run build
  - chmod +x dist
before_install:
  - npm i -g npm@6.14.x
before_deploy:
  - ls
  - ls dist
  - cd dist
deploy:
  - provider: script
    script: bash travis.sh
    skip_cleanup: true
    on:
      branch: master
notifications:
  email:
    on_failure: change
    on_success: change
